NHSDigital/validation-service-fhir-r4

Dockerfile
src/main/kotlin/com/example/fhirvalidator/configuration/ValidationConfiguration.kt
src/main/kotlin/com/example/fhirvalidator/controller/ValidateController.kt
src/main/resources/application.properties

Remove redundant cache of FHIR resources.
Limit tomcat to 10 worker threads.
Increase heap size to 2.5GB.
Add debug logging.

AEA-1024: Performance improvements.

---

src/main/kotlin/com/example/fhirvalidator/controller/ValidateController.kt
src/main/kotlin/com/example/fhirvalidator/util/ProfileApplier.kt

Test PR for IG Testing workflow

Reordered processing of capabilitystatements and messgedefinition.

---

src/main/kotlin/com/example/fhirvalidator/configuration/ApplicationConfiguration.kt

https://nhsd-jira.digital.nhs.uk/browse/AEA-1820

Changed from LenientErrorHandling to StrictErrorHandling

---

src/main/kotlin/com/example/fhirvalidator/configuration/ValidationConfiguration.kt
src/main/kotlin/com/example/fhirvalidator/controller/ValidateController.kt
src/main/kotlin/com/example/fhirvalidator/shared/RemoteTerminologyServiceValidationSupport.java
src/main/resources/manifest.json
src/test/kotlin/com/example/fhirvalidator/controller/ValidateControllerTest.kt

Moving change into testing branch

Initial commit for profile support for dose validation AEA-1876

---

src/main/kotlin/com/example/fhirvalidator/service/CapabilityStatementApplier.kt
src/main/kotlin/com/example/fhirvalidator/service/ImplementationGuideParser.kt
src/main/kotlin/com/example/fhirvalidator/service/MessageDefinitionApplier.kt

since the validationSupportChain does not support them

Switched message definitions and capability statements back to reading the package directly

---

.github/dependabot.yml
.github/pull_request_template.md
.github/workflows/continuous-integration.yml

- Use https://github.com/ncipollo/release-action to create a release as actions/create-release@v1 is not supported
- Add dependabot config 
- Add pull request template
**Check who should review this. Remove this line once this has been done**
:information_source: This section is to be filled in by the **reviewer**.

Use supported release-action

---

.github/workflows/dependabot_auto_approve_and_merge.yml

**Remove items from this list if they are not relevant. Remove this line once this has been done**
Use PAT for automerge
**Check who should review this. Remove this line once this has been done**
:information_source: This section is to be filled in by the **reviewer**.

use PAT for automerge

---

.github/workflows/dependabot_auto_approve_and_merge.yml

- use github app for auto approve dependabot pull requests
**Check who should review this. Remove this line once this has been done**
:information_source: This section is to be filled in by the **reviewer**.

use app for automerge

---

.github/workflows/merge_to_main.yml
.github/workflows/pull_request.yml
.github/workflows/quality_checks.yml
Makefile

- use workflows similar to other repos
- build docker image as part of build to make sure it works

Use github workflows as in other repos

---

.github/workflows/merge_to_main.yml

- fix release workflow so it has correct dependencies

fix workflow so it has correct dependencies

---

SECURITY.md

Docs: [AEA-4309] - add security.md

---

src/main/resources/manifest.json

Update: [AEA-4343] - Updated FHIR packages

---

Dockerfile

- update dependencies in dockerfile

Fix: [AEA-4417] - update dockerfile dependencies

---

README.md

Fix: [AEA-0000] - trigger build

---

Dockerfile

Fix: [AEA-0000] - really update dependencies

---

Dockerfile

- use alpine linux in dockerfile

Fix: [AEA-0000] - use alpine linux in dockerfile

---

pom.xml

- force update of packages to fix security issues

Fix: [AEA-0000] - fix security alerts

---

.github/workflows/merge_to_main.yml

Fix: [AEA-0000] - fix release workflow

---

.github/workflows/merge_to_main.yml

- fix dependency in release pipeline

Fix: [AEA-0000] - fix dependency in release pipeline

---

.github/workflows/combine-dependabot-prs.yml
.github/workflows/dependabot_auto_approve_and_merge.yml
.github/workflows/merge_to_main.yml
.github/workflows/pr-link.yml
.github/workflows/pr_title_check.yml

- pin ubuntu image used by github runner

Fix: [AEA-0000] - pin ubuntu version used by github runner

---

.gitignore
src/main/resources/manifest.json
src/test/resources/examples/primary-care/acute/no-nominated-pharmacy/medical-prescriber/author/gmc/responsible-party/din/IsleOfMan-1-Prepare-Request-200_OK.json
src/test/resources/examples/primary-care/acute/no-nominated-pharmacy/medical-prescriber/author/gmc/responsible-party/din/Wales-1-Prepare-Request-200_OK.json

- add examples for Isle of Man and Wales prescription types
- use latest simplifier package that includes Isle Of Man types

Fix: [AEA-4374] - add Isle of Man prescription types

---

src/main/resources/manifest.json

Update: [AEA-5434] - Updated NHSDigital package version
